### ISSUE TITLE
incorrect url 

### ISSUE THREAD

**Issue by h4arn** [bunchofbricks/librespot-snapcast#2]
`https://github.com/badaix/snapcast/releases/download/v0.26.0/snapserver_0.27.0-1_amd64.deb
`
doesn't work. i think it should be changed to 

`https://github.com/badaix/snapcast/releases/download/v0.27.0/snapserver_0.27.0-1_amd64.deb`

**Comment by bunchofbricks** [comment]
Fixed.
Due to changes in my home setup this repo was not really the source of my docker build. Then these mistakes might happen.
Won't be the case in future releases. Thanks for your hint.
